name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test android instrumentation
    runs-on: macos-latest
    strategy:
      matrix:
        config: [ { sdk: 21 }, { sdk: 33 }]

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run android instrumentation tests for sanity check
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.config.sdk }}
          script: ./gradlew :decompose-router:connectedDebugAndroidTest --stacktrace
